name: 'Hello world'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    descrpition: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    descrpition: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}